export const ALL_ARTS_SUCCESS = 'ALL_ARTS_SUCCESS';
export const ALL_ARTS_FAIL = 'ALL_ARTS_FAIL';

export const ALL_AUCTIONS_SUCCESS = 'ALL_AUCTIONS_SUCCESS';
export const ALL_AUCTIONS_FAIL = 'ALL_AUCTIONS_FAIL';

export const ALL_ARTS_FROM_AUCTION_SUCCESS = 'ALL_ARTS_FROM_AUCTION_SUCCESS';
export const ALL_ARTS_FROM_AUCTION_FAIL = 'ALL_ARTS_FROM_AUCTION_FAIL';

export const ART_DETAILS_SUCCESS = 'ART_DETAILS_SUCCESS';
export const ART_DETAILS_FAIL = 'ART_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL ';
