export const ALL_ARTS_SUCCESS = 'ALL_ARTS_SUCCESS';
export const ALL_ARTS_REQUEST = 'ALL_ARTS_REQUEST';
export const ALL_ARTS_FAIL = 'ALL_ARTS_FAIL';

export const ALL_AUCTIONS_SUCCESS = 'ALL_AUCTIONS_SUCCESS';
export const ALL_AUCTIONS_FAIL = 'ALL_AUCTIONS_FAIL';
export const ALL_AUCTIONS_REQUEST = 'ALL_AUCTIONS_REQUEST';

export const ALL_ADMIN_ARTS_REQUEST = 'ALL_ADMIN_ARTS_REQUEST';
export const ALL_ADMIN_ARTS_SUCCESS = 'ALL_ADMIN_ARTS_SUCCESS';
export const ALL_ADMIN_ARTS_FAIL = 'ALL_ADMIN_ARTS_FAIL';

export const ALL_ARTS_FROM_AUCTION_SUCCESS = 'ALL_ARTS_FROM_AUCTION_SUCCESS';
export const ALL_ARTS_FROM_AUCTION_FAIL = 'ALL_ARTS_FROM_AUCTION_FAIL';
export const ALL_ARTS_FROM_AUCTION_REQUEST = 'ALL_ARTS_FROM_AUCTION_REQUEST';

export const ADD_ARTS_TO_AUCTION_SUCCESS = 'ADD_ARTS_TO_AUCTION_SUCCESS';
export const ADD_ARTS_TO_AUCTION_FAIL = 'ADD_ARTS_TO_AUCTION_FAIL';
export const ADD_ARTS_TO_AUCTION_REQUEST = 'ADD_ARTS_TO_AUCTION_REQUEST';
export const ADD_ARTS_TO_AUCTION_RESET = 'ADD_ARTS_TO_AUCTION_RESET';

export const ART_DETAILS_SUCCESS = 'ART_DETAILS_SUCCESS';
export const ART_DETAILS_FAIL = 'ART_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL ';

export const GET_ADMIN_AUCTIONS_REQUEST = 'GET_ADMIN_AUCTIONS_REQUEST';
export const GET_ADMIN_AUCTIONS_SUCCESS = 'GET_ADMIN_AUCTIONS_SUCCESS';
export const GET_ADMIN_AUCTIONS_FAIL = 'GET_ADMIN_AUCTIONS_FAIL ';

export const CREATE_AUCTION_SUCCESS = 'CREATE_AUCTION_SUCCESS';
export const CREATE_AUCTION_FAIL = 'CREATE_AUCTION_FAIL';
export const CREATE_AUCTION_REQUEST = 'CREATE_AUCTION_REQUEST';
export const CREATE_AUCTION_RESET = 'CREATE_AUCTION_RESET';

export const UPDATE_AUCTION_SUCCESS = 'UPDATE_AUCTION_SUCCESS';
export const UPDATE_AUCTION_FAIL = 'UPDATE_AUCTION_FAIL';
export const UPDATE_AUCTION_REQUEST = 'UPDATE_AUCTION_REQUEST';
export const UPDATE_AUCTION_RESET = 'UPDATE_AUCTION_RESET';

export const AUCTION_DETAILS_SUCCESS = 'AUCTION_DETAILS_SUCCESS';
export const AUCTION_DETAILS_FAIL = 'AUCTION_DETAILS_FAIL';

export const CREATE_ART_SUCCESS = 'CREATE_ART_SUCCESS';
export const CREATE_ART_FAIL = 'CREATE_ART_FAIL';
export const CREATE_ART_REQUEST = 'CREATE_ART_REQUEST';
export const CREATE_ART_RESET = 'CREATE_ART_REQUEST';

export const UPDATE_ART_SUCCESS = 'UPDATE_ART_SUCCESS';
export const UPDATE_ART_FAIL = 'UPDATE_ART_FAIL';
export const UPDATE_ART_REQUEST = 'UPDATE_ART_REQUEST';
export const UPDATE_ART_RESET = 'UPDATE_ART_RESET';
